# Generated by Django 4.0.3 on 2022-03-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_a',
            fields=[
                ('cta_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cta_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='category_b',
            fields=[
                ('ctb_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ctb_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='recruiter',
            fields=[
                ('rid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('phno', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('stipend', models.FloatField()),
                ('location', models.CharField(max_length=50)),
                ('vacancies', models.IntegerField()),
                ('company_name', models.CharField(max_length=30)),
                ('experience', models.BooleanField(default=1)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateTimeField()),
                ('cat1', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rms.category_a')),
                ('cat2', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rms.category_b')),
                ('rec_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rms.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('cage', models.IntegerField()),
                ('cemail', models.EmailField(max_length=254)),
                ('cpassword', models.CharField(max_length=30)),
                ('cphno', models.CharField(max_length=10)),
                ('resume_link', models.FileField(upload_to='rms/resumes/')),
                ('job_cat', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rms.category_a')),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('app_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app_time', models.DateTimeField()),
                ('can_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rms.candidate')),
                ('rec_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rms.recruiter')),
            ],
        ),
    ]
