# Generated by Django 4.0.3 on 2022-03-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
