# Generated by Django 4.0.3 on 2022-03-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_recruiter_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
