# Generated by Django 4.0.3 on 2022-03-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0004_alter_recruiter_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
