# Generated by Django 4.0.3 on 2022-03-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0005_alter_recruiter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='description',
            field=models.TextField(default='', max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='rec_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rms.recruiter'),
        ),
    ]
