# Generated by Django 4.0.3 on 2022-03-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0006_jobs_description_alter_jobs_rec_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(default='', max_length=1500),
        ),
    ]
