# Generated by Django 4.0.3 on 2022-03-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0007_jobs_is_active_alter_jobs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rms.jobs'),
        ),
    ]
