# Generated by Django 4.0.3 on 2022-03-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0008_application_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_b',
            name='major_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rms.category_a'),
        ),
    ]
