# Generated by Django 4.0.3 on 2022-03-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0009_category_b_major_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cphno',
            field=models.CharField(max_length=20),
        ),
    ]
