# Generated by Django 4.0.3 on 2022-03-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0010_alter_candidate_cphno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='rec_id',
        ),
    ]
