# Generated by Django 4.0.3 on 2022-05-29 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phno', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('filled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='canddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(default='Others', max_length=10)),
                ('qualification', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=200)),
                ('course_type', models.CharField(max_length=30)),
                ('pass_year', models.CharField(max_length=4)),
                ('skills', models.CharField(max_length=300)),
                ('work_status', models.CharField(max_length=20)),
                ('experience', models.FloatField()),
                ('emp_status', models.BooleanField(default=False)),
                ('recent_comp', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('curr_city', models.CharField(max_length=100)),
                ('working_since', models.IntegerField()),
                ('curr_ctc', models.FloatField()),
                ('curr_fix_ctc', models.FloatField()),
                ('notice_period', models.CharField(max_length=10)),
                ('notice_nego', models.BooleanField()),
                ('industry', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=20)),
                ('exp_ctc', models.FloatField()),
                ('pref_job_type', models.CharField(max_length=15)),
                ('pref_emp_type', models.CharField(max_length=15)),
                ('pref_work_loc', models.CharField(max_length=30)),
                ('pref_work_ind', models.CharField(max_length=100)),
                ('pref_work_dept', models.CharField(max_length=100)),
                ('relocate', models.BooleanField()),
                ('send_updates', models.BooleanField()),
                ('resume_link', models.URLField()),
                ('cand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
        ),
    ]
