# Generated by Django 4.0.3 on 2022-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canddetails',
            name='course_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='curr_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='emp_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='gender',
            field=models.CharField(default='Others', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='industry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='job_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='notice_period',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='pass_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='pref_emp_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='pref_job_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='pref_work_dept',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='pref_work_ind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='pref_work_loc',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='qualification',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='recent_comp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='skills',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='specialization',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='university',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='canddetails',
            name='work_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='filled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phno',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
