# Generated by Django 4.0.3 on 2022-05-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recruiter',
            fields=[
                ('rid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('phno', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
